name: mpas-tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python =3.13
  - pip
  #
  # Jupyter Book v2
  - jupyter-book ==2.1.*
  #
  # Viz examples
  - cartopy
  - geopandas
  - geovista
  - jupyterlab
  - jupyterlab-myst
  - lonboard
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pandas
  - pyvista
  - xarray
  - uxarray >=2025.09.0
