[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = [
    "F",  # pyflakes
    "E",  # pycodestyle errors
    "B",  # flake8-bugbear
    "I",  # isort
    "UP",  # pyupgrade
    "ISC",  # flake8-implicit-str-concat
]

[tool.ruff.lint.isort]
known-first-party = ["WPSUtils"]

[tool.pytest.ini_options]
pythonpath = ["."]
filterwarnings = [
    "ignore:numpy.ndarray size changed:RuntimeWarning",
]
