name: GitHub Pages Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  BASE_URL: /${{ github.event.repository.name }}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash -leo pipefail {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Set up conda env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Install JB2
        run: python -m pip install -U --pre "jupyter-book==2.*" --no-deps -v

      # JB2 has --execute, but this way we can see how long it takes
      - name: Execute the notebook
        run: jupyter nbconvert --to notebook --execute --inplace 03-viz.ipynb
        env:
          PYVISTA_OFF_SCREEN: true

      - name: Build HTML
        run: jupyter book build --html --strict --ci

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./_build/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
