name: GitHub Pages Deploy

on:
  push:
    branches: [main]
env:
  BASE_URL: /${{ github.event.repository.name }}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Python
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Build HTML Assets
        run: jupyter-book build --html
        shell: micromamba-shell {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./_build/html"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
